# Base model path
base_model_path: /kaggle/input/datasets/maximnaddaf/model-weights/models/models/SVD/stable-video-diffusion-img2vid-xt-1-1
ckpt_path: /kaggle/input/datasets/maximnaddaf/model-weights/MimicMotion_1-1.pth

# Paths to unet and pose_net
unet_path: 
pos_net_path: 

# Input and output paths
video_folder: "/kaggle/input/datasets/maximnaddaf/solvo-videos/solvo_videos"
csv_path: "/kaggle/input/datasets/maximnaddaf/misc-data/misc/annotations_cleared_19.06.2023_SLOVO.csv"
embeddings_path: "/kaggle/input/datasets/maximnaddaf/misc-data/misc/gloss_embeddings_SLOVO.npy"
gloss_words_path: "/kaggle/input/datasets/maximnaddaf/misc-data/misc/gloss_words_SLOVO.txt"
output_dir: "outputs/"
no_use_float16: false
input_text: "Я очень тебя люблю"        # Provide text if needed
video_list: ""         # Provide a video list file if needed
log_file: "outputs/log.txt"

test_case:
  - ref_image_path: "/kaggle/working/RSL_VG/assets/example_data/images/b3994747-5ed0-4afb-a173-a8858dcde63c.jpeg"
    num_frames: 16
    resolution: 576
    frames_overlap: 6
    num_inference_steps: 25
    noise_aug_strength: 0
    guidance_scale: 2.0
    sample_stride: 2
    fps: 15
    seed: 42
